require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe OfferMessagesController do

  # This should return the minimal set of attributes required to create a valid
  # OfferMessage. As you add validations to OfferMessage, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "name" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # OfferMessagesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all offer_messages as @offer_messages" do
      offer_message = OfferMessage.create! valid_attributes
      get :index, {}, valid_session
      assigns(:offer_messages).should eq([offer_message])
    end
  end

  describe "GET show" do
    it "assigns the requested offer_message as @offer_message" do
      offer_message = OfferMessage.create! valid_attributes
      get :show, {:id => offer_message.to_param}, valid_session
      assigns(:offer_message).should eq(offer_message)
    end
  end

  describe "GET new" do
    it "assigns a new offer_message as @offer_message" do
      get :new, {}, valid_session
      assigns(:offer_message).should be_a_new(OfferMessage)
    end
  end

  describe "GET edit" do
    it "assigns the requested offer_message as @offer_message" do
      offer_message = OfferMessage.create! valid_attributes
      get :edit, {:id => offer_message.to_param}, valid_session
      assigns(:offer_message).should eq(offer_message)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new OfferMessage" do
        expect {
          post :create, {:offer_message => valid_attributes}, valid_session
        }.to change(OfferMessage, :count).by(1)
      end

      it "assigns a newly created offer_message as @offer_message" do
        post :create, {:offer_message => valid_attributes}, valid_session
        assigns(:offer_message).should be_a(OfferMessage)
        assigns(:offer_message).should be_persisted
      end

      it "redirects to the created offer_message" do
        post :create, {:offer_message => valid_attributes}, valid_session
        response.should redirect_to(OfferMessage.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved offer_message as @offer_message" do
        # Trigger the behavior that occurs when invalid params are submitted
        OfferMessage.any_instance.stub(:save).and_return(false)
        post :create, {:offer_message => { "name" => "invalid value" }}, valid_session
        assigns(:offer_message).should be_a_new(OfferMessage)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        OfferMessage.any_instance.stub(:save).and_return(false)
        post :create, {:offer_message => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested offer_message" do
        offer_message = OfferMessage.create! valid_attributes
        # Assuming there are no other offer_messages in the database, this
        # specifies that the OfferMessage created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        OfferMessage.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => offer_message.to_param, :offer_message => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested offer_message as @offer_message" do
        offer_message = OfferMessage.create! valid_attributes
        put :update, {:id => offer_message.to_param, :offer_message => valid_attributes}, valid_session
        assigns(:offer_message).should eq(offer_message)
      end

      it "redirects to the offer_message" do
        offer_message = OfferMessage.create! valid_attributes
        put :update, {:id => offer_message.to_param, :offer_message => valid_attributes}, valid_session
        response.should redirect_to(offer_message)
      end
    end

    describe "with invalid params" do
      it "assigns the offer_message as @offer_message" do
        offer_message = OfferMessage.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        OfferMessage.any_instance.stub(:save).and_return(false)
        put :update, {:id => offer_message.to_param, :offer_message => { "name" => "invalid value" }}, valid_session
        assigns(:offer_message).should eq(offer_message)
      end

      it "re-renders the 'edit' template" do
        offer_message = OfferMessage.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        OfferMessage.any_instance.stub(:save).and_return(false)
        put :update, {:id => offer_message.to_param, :offer_message => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested offer_message" do
      offer_message = OfferMessage.create! valid_attributes
      expect {
        delete :destroy, {:id => offer_message.to_param}, valid_session
      }.to change(OfferMessage, :count).by(-1)
    end

    it "redirects to the offer_messages list" do
      offer_message = OfferMessage.create! valid_attributes
      delete :destroy, {:id => offer_message.to_param}, valid_session
      response.should redirect_to(offer_messages_url)
    end
  end

end
